### ISSUE TITLE
Can't install pipeline. Requirement file needs to be updated.

### ISSUE THREAD

**Issue by steveschulze** [CIERA-Transients/POTPyRI#10]
Hi,

`conda env create -f pipeline_environment_[prefix].yml` doesn't work anymore. It returns a 50x error. 

```
conda env create  -f pipeline_environment_macosx.yml 
Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 502 BAD GATEWAY for url <http://astroconda.org/channel/main/osx-64/repodata.json>
Elapsed: 00:01.690848

A remote server error occurred when trying to retrieve this URL.

A 500-type error (e.g. 500, 501, 502, 503, etc.) indicates the server failed to
fulfill a valid request.  The problem may be spurious, and will resolve itself if you
try your request again.  If the problem persists, consider notifying the maintainer
of the remote server.
```

Removing `http://astroconda.org/channel/main` from the requirement file doesn't fix the problem.

```
POTPyRI % conda env create --name potpyri -f pipeline_environment_macosx.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - aom==3.5.0=h7ea286d_0
  - libblas==3.9.0=16_osxarm64_openblas
  - astroscrappy==1.1.0=py311h4add359_2
  - ca-certificates==2022.12.7=h4653dfc_0
  - libev==4.33=h642e427_1
  - hdf5==1.14.0=nompi_h6b85c65_103
  - libssh2==1.10.0=h7a5bd25_3
  - pthread-stubs==0.4=h27ca646_1001
  - libdeflate==1.17=h1a8c8d9_0
  - psutil==5.9.4=py311he2be06e_0
  - zfp==1.0.0=hb6e4faa_3
  - coverage==7.2.3=py311he2be06e_0
  - libcurl==7.88.1=h9049daf_1

...

```

Cheers,

Steve

**Comment by ikhrykin** [comment]
Most of the packages and specific builds in the environment yml file are not required by the pipeline. And many of them don't even exist anymore. 

You can just create a new environment with, say python 3.11.3, and then install all packages that are imported in the main_pipeline.py and a few extra that imported in other scripts (you can just run main_pipeline.py and install all the missing packages it will notify you about).

**Comment by steveschulze** [comment]
OK. I will try that.

Cheers,

Steve

From: Ilya Khrykin ***@***.***>
Reply to: CIERA-Transients/POTPyRI ***@***.***>
Date: Thursday, 20. June 2024 at 10:04
To: CIERA-Transients/POTPyRI ***@***.***>
Cc: Steve Schulze - HI ***@***.***>, Author ***@***.***>
Subject: Re: [CIERA-Transients/POTPyRI] Can't install pipeline. Requirement file needs to be updated. (Issue #10)


Most of the packages and specific builds in the environment yml file are not required by the pipeline. And many of them don't even exist anymore.

You can just create a new environment with, say python 3.11.3, and then install all packages that are imported in the main_pipeline.py and a few extra that imported in other scripts (you can just run main_pipeline.py and install all the missing packages it will notify you about).

**Comment by charliekilpatrick** [comment]
This has been resolved in the dev branch: https://github.com/CIERA-Transients/POTPyRI/tree/dev
