### ISSUE TITLE
Gemini GMOS z-band fringing.

### ISSUE THREAD

**Issue by jrastinejad** [CIERA-Transients/POTPyRI#14]
Example on burbidge in /data/Gemini/GMOS/GRB241105A_z_ep2/

No rush, thanks Charlie!

**Comment by charliekilpatrick** [comment]
This has been addressed by performing sky subtraction only in the z-band for Gemini/GMOS in order to self calibrate fringes.  The `/data/Gemini/GMOS/GRB241105A_z_ep2/` has been re-run and a new stack is available.
